### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by ginabeki** [ginabeki/space-travellers#25]
This is our react Kanban board.
We are working in a team of two. Members are as follow;
1. @mkaya13
2. @ginabeki
- Here's a [link](https://github.com/ginabeki/space-travellers/projects/4) to our Kanban

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Good implementations ✔️ 
- Nice issue summary ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far!   Please `assign` all cards to team members. You should see a circle with the user's avatar on each card 🙏🏼

![image](https://user-images.githubusercontent.com/63915024/208441544-7ddd9c80-a8c4-4499-91a1-3b1553f285a3.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ginabeki** [comment]
Hi @mukhammadrizooff we updated the allocation of tasks on Kanban.

**Comment by gemmen29** [comment]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights💯 
- Descriptive info ✔️ 
- Tasks distributed equally ✔️

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)


 ## Required Changes ♻️
- [ ] Kindly assign all cards to team members as requested by the previous reviewer, There is still one card that has not been assigned yet.
![image](https://user-images.githubusercontent.com/24703171/208453847-445edc34-3fca-4187-8383-96b1b4c2c821.png)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Davidosky007** [comment]
Hi @ginabeki  @mukhammadrizooff 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All info provided 👍 
* Tasks distributed evenly 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
